-- main.lua
local state = require("src/state")
local world = require("src/world")
local sprites = require("src/sprites")
local camera = require("src/camera")
local workers = require("src/workers")
local input = require("src/input")
local screen = require("src/screen")
local hud = require("src/ui/hud")
local menu = require("src/ui/menu")
local tree = require("src/buildings/tree")
local rock = require("src/buildings/rock")
local log_pile = require("src/buildings/log_pile")
local stone_pile = require("src/buildings/stone_pile")
local lumberyard = require("src/buildings/lumberyard")
local dormitory = require("src/buildings/dormitory")
local compactor = require("src/buildings/compactor")
local assembler = require("src/buildings/assembler")
local loading_dock = require("src/buildings/loading_dock")
local play_zone = require("src/buildings/play_zone")
local minesweeper = require("src/minesweeper")
local effects     = require("src/effects")
local sounds      = require("src/sounds")

function love.load()
  world.init(state)
  world.init_modules()
  sprites.load()
  sounds.load()
  tree.init(state)
  rock.init(state)
  log_pile.init(state)
  stone_pile.init(state)
  lumberyard.init(state)
  dormitory.init(state)
  compactor.init(state)
  assembler.init(state)
  loading_dock.init(state)
  play_zone.init(state)
  minesweeper.init(state)
end

function love.update(dt)
  state.update(dt)
  effects.update(dt)
  input.update(dt, state)
  camera.update(dt, state)
  workers.update(dt, state)
  tree.update(dt, state)
  rock.update(dt, state)
  compactor.update(dt, state)
  assembler.update(dt, state)
  loading_dock.update(dt, state)
  minesweeper.update(dt, state)
end

function love.draw()
  love.graphics.setColor(0.05, 0.05, 0.05)
  love.graphics.rectangle("fill", 0, 0, screen.dims())

  camera.attach(state)
  world.draw(state)
  workers.draw(state)
  menu.draw(state)
  camera.detach()

  hud.draw(state)
end

function love.mousepressed(x, y, button)
  input.mousepressed(state, x, y, button)
end

function love.keypressed(key)
  input.keypressed(state, key)
end

function love.wheelmoved(x, y)
  input.wheelmoved(state, x, y)
end
